services:
  # Rails Web Service
  - type: web
    name: patient-nutrition-api
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "bundle exec rails db:migrate"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: patient-nutrition-api-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2

databases:
  # PostgreSQL Database
  - name: postgres_patient_nutrition_api
    plan: free